### ISSUE TITLE
Incorrect parsed values for floats in arrays

### ISSUE THREAD

**Issue by ZtereoHYPE** [FoxSamu/json#1]
when a JSON string containing float values in an array gets parsed, those values turn to 0 in the parsed JsonNode.
These are a few examples:

colorgamut in original String of JSON:
![colorgamut in original String of JSON](https://user-images.githubusercontent.com/57519662/170789557-2116c64d-4d3f-417e-b811-8b0ad96b1825.png)

colorgamut once the String has been parsed with JSON.parse():
![colorgamut once the String has been parsed with JSON.parse()](https://user-images.githubusercontent.com/57519662/170789601-a1e7e9ae-cc60-4e2e-b5b6-f258b365d839.png)

xy in original string:
![Screenshot 2022-05-27 at 23 06 53](https://user-images.githubusercontent.com/57519662/170789723-073e6228-5d73-4664-bdc9-65382c54f540.png)

xy in parsed json
![Screenshot 2022-05-27 at 23 06 54](https://user-images.githubusercontent.com/57519662/170789764-ded029b4-5749-4a6d-bea1-77c3983ce441.png)

**Comment by FoxSamu** [comment]
Fixed in v0.3.1!
