### ISSUE TITLE
Use java 8

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [FoxSamu/json#2]
Some projects using this may require java 8, however this does not work in java 8.

**Comment by FoxSamu** [comment]
I will not use older Java versions. I make new projects compatible with the latest LTS version, nowadays Java 17, and Java 11 at the time of making this library.

Many systems have moved to newer Java versions, and Android desugars Java 11 neatly. Please use an alternative (e.g. Gson) if you really need to use Java 8.
